import Head from 'next/head'
import { Fragment } from 'react'
import Link from 'next/link'
import Image from 'next/image'

import { posts } from '../posts'

export default function Home() {
  return <>
    <Head>
      <title>Douglas Parsons' Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex-grow">
      <div className="grid sm:grid-cols-fr-auto gap-6">
        <div>
          <h2 className="text-xl font-medium">Hi, I'm Douglas 👋</h2>
          <p className="italic mt-6">
            I'm a software engineer currently at <a className="hover:underline text-teal-500" href="https://shamaazi.com" target="_blank">Shamaazi</a>.
          </p>
          <p className="italic mt-3">
            Soon joining ▲<a href="https://vercel.com" className="hover:underline text-teal-500" target="_blank">Vercel</a>.
          </p>
          <p className="italic mt-3">
            This is a place for my thoughts on programming and the world in general.
          </p>
        </div>
        <div className="rounded-full overflow-hidden w-32 h-32 border border-gray-200">
          <Image src="/me-nyx.jpg" width={128} height={128} objectFit="cover" />
        </div>
      </div>
      <div className="grid grid-cols-auto-fr gap-x-6 gap-y-8 mt-16">
        {posts.map((p) => {
          return <Fragment key={p.id}>
            <aside className="flex text-gray-500 items-center justify-end">{p.date}</aside>
            <Link href={`/posts/${p.id}`}><a className="hover:underline text-lg cursor-pointer font-semibold">{p.title}</a></Link>
          </Fragment>
        })}
      </div>
    </main>
  </>
}
